version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      USE_DATABASE: "false"
    volumes:
      - .:/app
    command: ["poetry", "run", "uvicorn", "apps.backend.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
