name: 'Setup Python with Poetry'
description: 'Install Python and Poetry using actions/setup-python and cache'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
    - name: Install Poetry and uv
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry uv
