name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: npm install -g pnpm@8
      - run: pnpm install
      - run: pnpm test --if-present
      - run: mkdir -p artifact && echo "placeholder" > artifact/placeholder.txt
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: artifact
